export const EXERCISE_ADDED = 'EXERCISE_ADDED';
export const EXERCISE_UPDATED = 'EXERCISE_UPDATED';
export const EXERCISE_REMOVED = 'EXERCISE_REMOVED';

export const SESSION_ADDED = 'SESSION_ADDED';
export const SESSION_UPDATED = 'SESSION_UPDATED';
export const SESSION_DELETED = 'SESSION_DELETED';

export const SESSION_EXERCISE_ADDED = 'SESSION_EXERCISE_ADDED';

export const TRAINING_SET_ADDED = 'TRAINING_SET_ADDED';
