export const EXERCISE_ADDED = 'EXERCISE_ADDED';
export const EXERCISE_UPDATED = 'EXERCISE_UPDATED';
export const EXERCISE_REMOVED = 'EXERCISE_REMOVED';

export const SESSION_ADDED = 'SESSION_ADDED';
export const SESSION_UPDATED = 'SESSION_UPDATED';
export const SESSION_DELETED = 'SESSION_DELETED';

export const SESSION_EXERCISE_ADDED = 'SESSION_EXERCISE_ADDED';
export const SESSION_EXERCISE_REMOVED = 'SESSION_EXERCISE_REMOVED';
export const SESSION_EXERCISE_UPDATED = 'SESSION_EXERCISE_UPDATED';

export const TRAINING_SET_ADDED = 'TRAINING_SET_ADDED';
export const TRAINING_SET_REMOVED = 'TRAINING_SET_REMOVED';
export const TRAINING_SET_UPDATED = 'TRAINING_SET_UPDATED';

export const SET_SESSION_ID = 'SET_SESSION_ID';
export const SET_EXERCISE_ID = 'SET_EXERCISE_ID';
